name: CD
on:
    workflow_call: 
        inputs:
          manifests: 
            type: string
            required: true
            description: "Arquivos de manifesto que serão alterados"
          images: 
            type: string
            required: true
            description: "Imagens que serão alteradas nos manifestos"
        secrets:
          kubeconfig:
            required: true
            description: "Kubeconfig para configurar o contexto do Kubernetes"
jobs:
    job-exemplo:
      runs-on: ubuntu-latest
      steps:
        - name: Comando Exemplo
          run: echo "Teste de Execução"
    deploy-kubernetes:
        runs-on: ubuntu-latest
        steps:
            - name: Obtendo o código
              uses: actions/checkout@v4.1.5
            - name: Configuração de contexto do Kubernetes
              uses: azure/k8s-set-context@v4.0.0
              with:
                method: kubeconfig
                kubeconfig: ${{ secrets.kubeconfig }}
            - name: Execução do Manifesto
              uses: Azure/k8s-deploy@v5
              with:
                manifests: ${{ inputs.manifests }}
                images: ${{ inputs.images }}