name: CI
on: 
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Obtendo o código
      uses: actions/checkout@v4.1.5
    - name: Autenticação no Docker Hub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build da Imagem Docker
      uses: docker/build-push-action@v5.3.0
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: | 
          fabricioveronez/aula-primeira-pipeline:v${{ github.run_number }} 
          fabricioveronez/aula-primeira-pipeline:latest 
  CALL-CD:
    needs: [CI]
    uses: fabricioveronez/k8s-cd-teste/.github/workflows/cd.yaml@main
    with: 
      manifests: |
        k8s/deployment.yaml
      images: |
        fabricioveronez/aula-primeira-pipeline:v${{ github.run_number }} 
    secrets:
      kubeconfig: ${{ secrets.K8S_CONFIG }}
